CREATE TABLE CART(
  ORDERNO CHAR(16) PRIMARY KEY NOT NULL,
  STATUS CHAR(15) NOT NULL
);

CREATE TABLE PRODUCT(
  PRODUCTID CHAR(16) PRIMARY KEY NOT NULL,
  NAME CHAR(20) NOT NULL,
  PRICE DECIMAL(7, 2) NOT NULL,
  QUANTITY INTEGER NOT NULL
);

CREATE TABLE USER(
  USERID CHAR(16) PRIMARY KEY NOT NULL
);

CREATE TABLE FILLCART(
  PRODUCTID CHAR(16) NOT NULL,
  ORDERNO CHAR(16) NOT NULL,
  QUANTITY INTEGER NOT NULL,
  FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
  FOREIGN KEY(ORDERNO) REFERENCES CART(ORDERNO)
);

CREATE TABLE ORDERCART(
  USERID CHAR(16) NOT NULL,
  ORDERNO CHAR(16) NOT NULL,
  BILLINGADDR CHAR(50) NULL,
  SHIPPINGDDR CHAR(50) NULL,
  CCNUMBER CHAR(16) NULL,
  CCNAME CHAR(30) NULL,
  CVV CHAR(3) NULL,
  DATEANDTIME DATETIME NULL,
  PURCHASED BOOLEAN DEFAULT 0,
  FOREIGN KEY(ORDERNO) REFERENCES CART(ORDERNO),
  FOREIGN KEY(USERID) REFERENCES USER(USERID)
);
