CREATE TABLE CART(
  ORDERNO INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  STATUS CHAR(15) NOT NULL,
  NOTE CHAR(255) NULL
);

CREATE TABLE PRODUCT(
  PRODUCTID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME CHAR(32) NOT NULL,
  PRICE DECIMAL(7, 2) NOT NULL,
  QUANTITY INTEGER NOT NULL,
  DESCR CHAR(128) NOT NULL
);

CREATE TABLE USER(
  USERID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  EMAIL CHAR(50) NOT NULL
);

CREATE TABLE FILLCART(
  PRODUCTID INTEGER NOT NULL,
  ORDERNO INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL,
  FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
  FOREIGN KEY(ORDERNO) REFERENCES CART(ORDERNO)
);

CREATE TABLE ORDERCART(
  USERID INTEGER NOT NULL,
  ORDERNO INTEGER NOT NULL,
  BILLINGADDR CHAR(50) NULL,
  SHIPPINGADDR CHAR(50) NULL,
  CCNUMBER CHAR(16) NULL,
  CCNAME CHAR(30) NULL,
  CVV CHAR(3) NULL,
  PURCHASED BOOLEAN DEFAULT 0,
  FOREIGN KEY(ORDERNO) REFERENCES CART(ORDERNO),
  FOREIGN KEY(USERID) REFERENCES USER(USERID)
);


INSERT INTO CART (STATUS) VALUES ('Not Shipped');
INSERT INTO CART (STATUS) VALUES ('Not Shipped');
INSERT INTO CART (STATUS) VALUES ('Not Shipped');
INSERT INTO CART (STATUS) VALUES ('Not Shipped');
INSERT INTO CART (STATUS) VALUES ('Not Shipped');


INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Candy Lobster', 12.99, 4, "A realll big hunkin lobster boi!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Jolly Rancher', 5.99, 200, 'Comes in all different colors, guranteed to break your teeth!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Milk Duds', 1.99, 50, "Caramel candy that looks like your rabbit's droppings!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Baby Ruth', 3.99, 100, 'A lesser version of Ferrero Rocher, ironically made owned by the same company!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Star Burts', 5.99, 500, "Doesn't look like a star, not busting with flavor, but they're popular!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Sweet Tarts', 6.99, 300, 'Collored Mentos in a foil wrapped tube!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Kit Kats', 500.00, 500, 'This is a staple to a good Halloween candy!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Reeses', 19.99, 200, 'Peanut Butter filled chocolate cups that never come off the wrapper in one piece!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Werthers', 1.99, 50, 'A candy only a Grandmother could love!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Pop Rocks', 12.99, 200, "It's like chewing on colorful sand that pops!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('JawBreakers', 15.99, 100, 'Everybody knows the Cartoon Network show these starred in!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Twizzlers', 13.99, 300, "Wax like rope candy, don't smack your friends with them, they sting!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Smarties', 14.99, 400, 'Ironically, these have nothing to do with intellect!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Mr.Goodbar', 16.99, 100, 'Legally this cannot be advertized as milk chocolate!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('BlowPops', 17.99, 200, "Combination of a sucker and bubblegum it's quite unique!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Milky Way', 18.99, 300, "Another generic caramel and chocolate bar, who's name was taken from a milkshake!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Snickers', 19.99, 400, "You're not you when you're '"      "'!");
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Dots', 14.99, 100, 'An alternate version to "Jujubes" also found in a popular Cartoon Network show!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Hersheys Chocolate Bar', 15.99, 200, 'The original chocolate bar, "The founder of all chocolate bars"!');
INSERT INTO PRODUCT (NAME, PRICE, QUANTITY, DESCR) VALUES ('Twix', 17.99, 500, 'Left or right, they taste exactly the same!');


INSERT INTO USER (EMAIL) VALUES ('LehutaIsTheMan@gmail.com');
INSERT INTO USER (EMAIL) VALUES ('JabariIsTheGoat@gmail.com');
INSERT INTO USER (EMAIL) VALUES ('TheRadBrad@gmail.com');
INSERT INTO USER (EMAIL) VALUES ('DannyPhantom@gmail.com');
INSERT INTO USER (EMAIL) VALUES ('KennyBoBenny@gmail.com');


INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (18, 3, 10);
INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (4, 3, 6);
INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (9, 1, 10);
INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (10, 5, 7);
INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (20, 2, 3);
INSERT INTO FILLCART (PRODUCTID, ORDERNO, QUANTITY) VALUES (18, 2, 10);


INSERT INTO ORDERCART (USERID, ORDERNO, BILLINGADDR, SHIPPINGADDR, CCNUMBER, CCNAME, CVV, PURCHASED)
  VALUES (1, 2, '900 Crane Dr. DeKalb IL, 60115', '900 Crane Dr. DeKalb IL, 60115', 1234567891234567, 'This Guy', 123, 1);
INSERT INTO ORDERCART (USERID, ORDERNO, BILLINGADDR, SHIPPINGADDR, CCNUMBER, CCNAME, CVV, PURCHASED)
  VALUES (2, 1, '475 That St. Elgin IL, 60123', '475 That St. Elgin IL, 60123', 1234567891234567, 'That Guy', 123, 1);
INSERT INTO ORDERCART (USERID, ORDERNO, BILLINGADDR, SHIPPINGADDR, CCNUMBER, CCNAME, CVV, PURCHASED)
  VALUES (3, 5, '123 Another St. SomeTown IL, 60123', '123 Another St. SomeTown IL, 60123', 1234567899999999, 'Another Guy', 321, 0);
INSERT INTO ORDERCART (USERID, ORDERNO, BILLINGADDR, SHIPPINGADDR, CCNUMBER, CCNAME, CVV, PURCHASED)
  VALUES (4, 3, '999 Another St. SomeTown IL, 60123', '999 Another St. SomeTown IL, 60123', 1234567899999888, 'Some other Guy', 325, 1);
INSERT INTO ORDERCART (USERID, ORDERNO, BILLINGADDR, SHIPPINGADDR, CCNUMBER, CCNAME, CVV, PURCHASED)
  VALUES (5, 4, '666 Some Other St. SomeTown IL, 60123', '666 Some Other St. SomeTown IL, 60123', 1234567899999997, 'Dumb Guy', 876, 0);
